version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - yum install -y nodejs
      - echo installing yarn...
      - yum install --no-install-recommends yarn
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/app